version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    restart: on-failure
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      
  collector:
    image: jaegertracing/jaeger-collector:1.8
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200/
    ports:
      - "14269"
      - "14268:14268"
      - "14267"
      - "14250"
      - "9411:9411"
    depends_on:
      - kibana
    links:
      - elasticsearch
    command: ["--es.server-urls=http://elasticsearch:9200/","--es.tags-as-fields.all=true", "--es.num-shards=1", "--span-storage.type=elasticsearch"]
    restart: on-failure

  agent:
    image: jaegertracing/jaeger-agent:1.8
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
    command: ["--collector.host-port=collector:14267"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    depends_on:
      - collector
    links:
      - collector
    restart: on-failure

  query:
    image: jaegertracing/jaeger-query:1.8
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200/
    ports:
      - "16686:16686"
      - "16687"
    command: ["--es.server-urls=http://elasticsearch:9200", "--span-storage.type=elasticsearch", "--log-level=debug"]
    depends_on:
      - agent
    links:
      - elasticsearch
    restart: on-failure
